# -*- coding: utf-8 -*-
"""DataSciencePython.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/190xHLVHBOv3glHht-RgaHQYGN3P1-oKo

Installation Requirements
"""

pip install pandas numpy matplotlib seaborn

""" Importing Libraries"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

""" Loading Dataset"""

#Load dataset
file_path='netflix_titles.csv'
df=pd.read_csv(file_path)

# Display first 5 rows
print(df.head())

"""Understanding Dataset"""

# Dataset information
print(df.info())

#Statistical summary
print(df.describe())
#Null values
print(df.isnull().sum)

"""Data Cleaning

Handling Missing Values
"""

#Filling missing values
#Director
df['director'].fillna('Unknown',inplace=True)
#Cast
df['cast'].fillna('Unknown',inplace=True)
#Country
df['country'].fillna('Unknown',inplace=True)
#Date_added
df['date_added'].fillna('Unknown',inplace=True)
# Rating
df['rating'].fillna(df['rating'].mode()[0], inplace=True)
#Duration
df['duration'].fillna('Unknown',inplace=True)

"""Removing Duplicates"""

# Remove duplicate rows
df.drop_duplicates(inplace=True)

""" Exploratory Data Analysis (EDA)

 Movies vs TV Shows
"""

plt.figure(figsize=(6,5))
sns.countplot(x='type', data=df)
plt.title('Movies vs TV Shows')
plt.show()

"""Most Popular Genres"""

# Extract genres
genres = df['listed_in'].str.split(', ', expand=True).stack()

# Count genres
genre_count = genres.value_counts().head(10)

# Plot
plt.figure(figsize=(12,6))
genre_count.plot(kind='bar')
plt.title('Top 10 Genres on Netflix')
plt.xlabel('Genre')
plt.ylabel('Count')
plt.show()

"""Ratings Analysis"""

plt.figure(figsize=(10,6))
sns.countplot(y='rating', data=df, order=df['rating'].value_counts().index)
plt.title('Content Ratings Distribution')
plt.show()