CREATE DATABASE PROJECT;
USE PROJECT;
CREATE TABLE E_COMMERCE(SNO INT PRIMARY KEY,CUSTOMER_NAME VARCHAR(50),CUSTOMER_AGE INT,PUR_DATE DATE,PRODUCT_NAME VARCHAR(50),PRICE INT);
INSERT INTO E_COMMERCE VALUES(01,"AKILAN",24,"2026-05-01","MOBILE",40000),
(02,"ARUNA",27,"2026-05-01","AC",50000),
(03,"BHANU",29,"2026-05-02","WASHING_MACHINE",35000),
(04,"CHITRA",32,"2026-05-03","MOBILE",30000),
(05,"DHARINY",22,"2026-05-03","AC",40000);
SELECT * FROM E_COMMERCE;
#AVERAGE SALES 
SELECT AVG(PRICE) FROM E_COMMERCE;
#SALES PER DAY
SELECT * FROM E_COMMERCE WHERE PUR_DATE="2026-05-01";
SELECT * FROM E_COMMERCE WHERE PUR_DATE="2026-05-02";
SELECT * FROM E_COMMERCE WHERE PUR_DATE="2026-05-03";
#NUMBER OF TIMES CUSTOMER PURCHASED(CUSTOMER BEHAVIOUR)
SELECT COUNT(PRICE) FROM E_COMMERCE WHERE PRODUCT_NAME="MOBILE";
SELECT COUNT(PRICE) FROM E_COMMERCE WHERE PRODUCT_NAME="AC";
SELECT COUNT(PRICE) FROM E_COMMERCE WHERE PRODUCT_NAME="WASHING_MACHINE";
#SALES OF PRODUCT
SELECT SUM(PRICE) FROM E_COMMERCE WHERE PRODUCT_NAME="MOBILE";
SELECT SUM(PRICE) FROM E_COMMERCE WHERE PRODUCT_NAME="AC";
SELECT SUM(PRICE) FROM E_COMMERCE WHERE PRODUCT_NAME="WASHING_MACHINE";
#TOP SELLING PRODUCT
SELECT AVG(PRICE) FROM E_COMMERCE WHERE PRODUCT_NAME="MOBILE";
SELECT AVG(PRICE) FROM E_COMMERCE WHERE PRODUCT_NAME="AC";
SELECT AVG(PRICE) FROM E_COMMERCE WHERE PRODUCT_NAME="WASHING_MACHINE";
DROP DATABASE PROJECT;