# -*- coding: utf-8 -*-
"""PythonToExcel.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z5bGgbLnX8Sz_oMSm-_-R5XiHbrxf2i0
"""

import pandas as PD
Names=[]
Ages=[]
Genders=[]
Qualifications=[]
N=int(input("Enter the number of person"))
for i in range(N):
  name_value=input("Enter the name")
  age_value=input("Enter the age")
  gender_value=input("Enter the gender")
  qualification_value=input("Enter the qualification")
  Names.append(name_value)
  Ages.append(age_value)
  Genders.append(gender_value)
  Qualifications.append(qualification_value)
dict={"Name":Names,
      "Age":Ages,
      "Gender":Genders,
      "Qualification":Qualifications}
lis=PD.DataFrame(dict)
lis.to_csv("HR_dataset.csv",index=False)