# -*- coding: utf-8 -*-
"""PYTHON TO SQL

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ay-RpFwo1f-7LouDcdOvIaCgZ73Vv2zi

Install MySQL Connector
"""

pip install mysql-connector-python

"""Database Connection"""

import mysql.connector

conn = mysql.connector.connect(
    host="localhost",
    port=3306,
    user="root",
    password="password",
    database="company"
)

cursor = conn.cursor()

""" Add Employee"""

def add_employee():
    name = input("Enter Name: ")
    dept = input("Enter Department: ")
    salary = float(input("Enter Salary: "))
    date = input("Enter Joining Date (YYYY-MM-DD): ")
    query = '''
    INSERT INTO employees
    (name, department, salary, joining_date)
    VALUES (%s,%s,%s,%s)
    '''
    values = (name, dept, salary, date)
    cursor.execute(query, values)
    conn.commit()

""" View Employees"""

def view_employees():
    cursor.execute("SELECT * FROM employees")
    data = cursor.fetchall()
    for row in data:
        print(row)

"""Search Employee"""

def search_employee():
    emp_id = int(input("Enter Employee ID: "))
    query = "SELECT * FROM employees WHERE emp_id=%s"
    cursor.execute(query, (emp_id,))
    result = cursor.fetchone()
    print(result)

""" Update Employee Salary"""

def update_salary():
    emp_id = int(input("Enter Employee ID: "))
    salary = float(input("Enter New Salary: "))
    query = '''
    UPDATE employees
    SET salary=%s
    WHERE emp_id=%s
    '''
    cursor.execute(query, (salary, emp_id))
    conn.commit()

""" Delete Employee"""

def delete_employee():
    emp_id = int(input("Enter Employee ID: "))
    query = "DELETE FROM employees WHERE emp_id=%s"
    cursor.execute(query, (emp_id,))
    conn.commit()

"""
Salary Report using Pandas
"""

import pandas as pd

def salary_report():
    query = '''
    SELECT department, AVG(salary)
    FROM employees
    GROUP BY department
    '''
    df = pd.read_sql(query, conn)
    print(df)